### ISSUE TITLE
Terminal only return one line

### ISSUE THREAD

**Issue by StrideZhou** [IoTServ/McuNode-Lib#1]
only few times can return multiple lines.
if we can discuss in Chinese is best.

**Comment by IoTServ** [comment]
Someone use Old nodemcu-firmware may return first line，last nodemcu firmware is ok，you can hava a try.

**Comment by StrideZhou** [comment]
ok !thanks a lot ,I'll give it a try

**Comment by IoTServ** [comment]
you are welcome

**Comment by StrideZhou** [comment]
test pass!
BUT another problem pop up
I fixed it 
I will open a pull request

**Comment by IoTServ** [comment]
ok thanks！
