### ISSUE TITLE
PANIC: unprotected error in call to Lua API (mcunode.lua:103: out of memory)

### ISSUE THREAD

**Issue by StrideZhou** [IoTServ/McuNode-Lib#3]
I have a big html file and when I send it
The mcu gaves me this message
`PANIC: unprotected error in call to Lua API (mcunode.lua:103: out of memory)`
line 103 is `conn:send(line)`
search the NodeMCU Documentation I found this
[http://nodemcu.readthedocs.io/en/master/en/modules/net/#netsocketsend](url)
seems like `conn:send()` can't stay in `while true`
I fix this by this code
```lua
local function render(conn,res)
    local body = nil
    local attr = res.attribute
    html=""
    if res.file then
        --print("file")
        file.open(res.file,"r")
        --print("response file : " .. res.file) 
        local function sendf(localSocket)
            local line = file.readline()
            if attr then
                for k, v in pairs(attr) do
                    line= string.gsub(line, '{{'..k..'}}', v)
                end
            end
            if line ~= nil then
                --html=html..line
                conn:send(line)
                line = nil 
            else
                --localSocket:close()
                file.close()
                --return
            end     
        end
        conn:on("sent", sendf)
        sendf(conn)
    elseif res.body  then
```
but this code does not work well 
it only return one or two lines
seems like the problem connected to the server some how

**Comment by IoTServ** [comment]
These may be due to the nodemcu data to the server timeout caused by the server cannot know what time nodemcu  sent data over, so when the design is received once data is returned to the browser.The server may be some improvement later

**Comment by IoTServ** [comment]
Server Once receive data then return ,DO NOT KNOWN the data over or not, wait more time for the data may fix most of problems.

**Comment by StrideZhou** [comment]
ok!Looking forward to your update.

**Comment by IoTServ** [comment]
:)

**Comment by IoTServ** [comment]
https://github.com/IoTServ/McuNode-server/blob/28a3d02794496784f162775ad36a11a7f6024f91/mcunode/controllers/proxy.go#L34   

update but NOT tested！dot play nodemcu recently，release file build today.

**Comment by IoTServ** [comment]
你是国内的啊，可以加qq聊

**Comment by StrideZhou** [comment]
stride_anderson@qq.com
qq号发邮件说吧😂😂😂
